"""empty message

Revision ID: b6f1b9267d8e
Revises: ed27459bc5bf
Create Date: 2020-05-24 15:38:41.665688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f1b9267d8e'
down_revision = 'ed27459bc5bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'level', ['name'])
    op.create_unique_constraint(None, 'level', ['priority'])
    op.add_column('score_board_detail', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score_board_detail', 'feedback')
    op.drop_constraint(None, 'level', type_='unique')
    op.drop_constraint(None, 'level', type_='unique')
    # ### end Alembic commands ###
